# Deployment Set
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      appname: springboot
      version: blue
  template:
    metadata:
      name: mavenwebapp
      labels:
        appname: springboot
        version: blue
    spec:
      containers:
      - name: mavenspringboot
        image: modugulakrishna99/java-docker-swarm:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
...
# service -nodePort
apiVersion: v1
kind: Service
metadata:
  name: javaspringsvc

spec:
  selector:
    appname: javaspringboot
    version: green            # ------> Label of Pod
  type: NodePort
  ports:
  - port: 80                  #------> service port
    targetPort: 8080           #------> container port
    nodePort: 32000
...
